discount:
  newDiscountPeriod: 2000
  listDiscountPeriod: 6000
##########################################################################################         
myenv:
  host: localhost 
##########################################################################################         
server:
  port: 8080
##########################################################################################           
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
##########################################################################################         
management:
  endpoints:
    web:
      exposure:
        include: 
          - info
          - health
          - metrics
          - dump
          - heapdump
          - env
          - beans
          - autoconfig
          - configprops
          - trace
          - mappings
          - api
  metrics:
    export:
      atlas:
        enabled: true
##########################################################################################             
camel:
  springboot:
    main-run-controller: true
  component:
    servlet:
      mapping:
        contextPath: /sensha4u/*
##########################################################################################         
  